# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKE1y61vYZbqe0szi9Y5DpJSk9Tq9CqH
"""

import pandas as pd
import requests

response=requests.get('https://apikey_of_movie_website')
print(response.status_code)

df=pd.DataFrame(response.json())
print(df)

df.to_csv("movies")

from google.colab import drive
drive.mount('/content/drive')