# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xk8wQeg0MJfoL9-CW00P5rj5kQQ8nIj_
"""

import requests
from bs4 import BeautifulSoup

url = "https://books.toscrape.com/catalogue/category/books/travel_2/index.html"

webpage = requests.get(url).text
soup=BeautifulSoup(webpage, "lxml")

travel = []

books = soup.select("article.product_pod")

print(len(books))

for book in books:
    travel.append(book.select_one("img")["alt"])

print(travel)
